# Generated by Django 5.2.6 on 2025-10-24 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('movie_title', models.CharField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('song_name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='songs/audio/')),
                ('cover_image', models.ImageField(upload_to='songs/covers/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
