# Generated by Django 5.2.6 on 2025-10-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_playlist_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='myapp.song'),
        ),
    ]
